#ifndef LIBBQTNCONNECT_GLOBAL_H
#define LIBBQTNCONNECT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBBQTNCONNECT_LIBRARY)
#  define LIBBQTNCONNECTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LIBBQTNCONNECTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBBQTNCONNECT_GLOBAL_H
